### ISSUE TITLE
If backend response is 500, cached object is blown, 500 is returned

### ISSUE THREAD

**Issue by ericandrewlewis** [mattiasgeniar/varnish-4.0-configuration-templates#24]
I've configured a server to serve grace cached content to users like so, [as described in Varnish docs](https://www.varnish-cache.org/docs/trunk/users-guide/vcl-grace.html).

```vcl
sub vcl_hit {
   if (obj.ttl >= 0s) {
       // A pure unadultered hit, deliver it
       return (deliver);
   }
   if (obj.ttl + obj.grace > 0s) {
       // Object is in grace, deliver it
       // Automatically triggers a background fetch
       return (deliver);
   }
   // fetch & deliver once we get the result
   return (fetch);
}
```

I'm noticing that when a backend request is made in the grace period (e.g. if the TTL is 120 and the grace cache is 1 hour, 121 seconds after the initial request was cached) and the back-end is serving 500s, that request is served from the cache, but subsequent requests return 500s.

I've implemented this sort of logic to prevent cache busting when the backend serves 500s
```vcl
sub vcl_backend_response {
    if (beresp.status == 500 || beresp.status == 502 || beresp.status == 503 || beresp.status == 504) {
        return (abandon);
    }
    # ... more code
}
```

**Comment by mattiasgeniar** [comment]
Very good point, I've implemented this change in the main VCL. Thanks for the contribution!

**Comment by shawnsi** [comment]
Does this change make error responses outright uncacheable?  It seems there should be a condition to determine if the request is in grace mode before abandoning responses.

**Comment by LukeHandle** [comment]
This is currently placed after the TTL catchall and for me is being missed:
```
  # Set 2min cache if unset for static files
  if (beresp.ttl <= 0s || beresp.http.Set-Cookie || beresp.http.Vary == "*") {
    set beresp.ttl = 120s; # Important, you shouldn't rely on this, SET YOUR HEADERS in the backend
    set beresp.uncacheable = true;
    return (deliver);
  }

  # Don't cache 50x responses
  if (beresp.status == 500 || beresp.status == 502 || beresp.status == 503 || beresp.status == 504) {
    return (abandon);
  }
```

And from log you can see we set TTL to 120 before delivering:
```
--  BerespProtocol HTTP/1.1
--  BerespStatus   504
--  BerespReason   Gateway Time-out
--  BerespHeader   Server: nginx
--  BerespHeader   Date: Sun, 17 Sep 2017 17:39:12 GMT
--  BerespHeader   Content-Type: text/html; charset=utf-8
--  BerespHeader   Content-Length: 578
--  BerespHeader   Connection: keep-alive
--  TTL            RFC -1 10 -1 1505669952 1505669952 1505669952 0 0
--  VCL_call       BACKEND_RESPONSE
--  TTL            VCL 120 10 0 1505669952
--  VCL_return     deliver
--  Storage        malloc s0
```

I am trying though to implement some sort of grace usage for a backend "error" like this, likely needs some sort of retry/restart with header set.

**Comment by markvincze** [comment]
@shawnsi Have you found a way to achieve this?  
I'd like to do the same: if the response is not in the cache at all, then return the `5xx` to the client, but if it's in the cache, then return the cached value instead for the grace period.

**Comment by markvincze** [comment]
I think I found a way since then, the key was to use `is_bgfetch` to check if we're in a situation when we still have a cached object in the grace period. So this setup did the trick for me:

```
sub vcl_backend_response {
    # Happens after we have read the response headers from the backend.
    # Here you clean the response headers and other mistakes your backend does.

    # This block will make sure that if the upstream returns a 5xx, but we have the response in the cache (even if it's expired),
    # we fall back to the cached value (until the grace period is over).
    if (beresp.status == 500 || beresp.status == 502 || beresp.status == 503 || beresp.status == 504)
    {
        # This check is important. If is_bgfetch is true, it means that we've found and returned the cached object to the client,
        # and triggered an asynchoronus background update. In that case, if it was a 5xx, we have to abandon, otherwise the previously cached object
        # would be erased from the cache (even if we set uncacheable to true).
        if (bereq.is_bgfetch)
        {
            return (abandon);
        }

        # Even if we couldn't send a previous successful response from the cache, we should never cache a 5xx response.
        set beresp.uncacheable = true;
    }

    # Set the grace time to 2 hours.
    # Gives the posibility to serve backend traffic from cache if backend is down
    set beresp.grace = 2h;

    # The object's remaining time to live.
    set beresp.ttl = 10m;
}
```

I hope I didn't miss any edge case.

**Comment by hvelarde** [comment]
just to clarify: `is_bgfetch` was added in Varnish 5.2.

**Comment by bfis108137** [comment]
What I want to do is remember that we got the error and not make another request for another 30 seconds but still continue to serve the old object which doesn't have an error

**Comment by markvincze** [comment]
@bfis108137,

I'm not sure how you could achieve not making another request for 30 seconds. With the grace period you can achieve still returning the old object, but Varnish will also try to refresh the object every time.

Btw after investigating the original issue, I've blogged about my findings here: https://blog.markvincze.com/how-to-gracefully-fall-back-to-cache-on-5xx-responses-with-varnish/, maybe this contains some useful info.

**Comment by bfis108137** [comment]
The point would be that there is a reason that there is an error.  If it's a ddos attack then I don't want all those requests.  If it's because of overload on the server then also I want to wait some time.  By not saving delaying the requests, I am possibly making things worse.

**Comment by bfis108137** [comment]
The way you propose is probably the best bet.  You save yourself from being attacked on uncached urls and are only vunerable on the cached ones.

**Comment by bfis108137** [comment]
another option is saint mode which is a module.  I would install it but our varnish is managed by someone higher up in our parent org and I know him.  There is no way he will add it.  He is afraid to make too many changes because the varnish has more than 20 websites being served by it.  vcl changes are fine but no modules.
